#!/usr/bin/env expect

set timeout 1

set ::env(EXAMPLE_FOO) 42
set ::env(EXAMPLE_FOO_BAR) 43

spawn ./bin/example
expect {
    default { puts "FAIL"; exit 1 }
    "foo: \"42\""
}
expect {
    default { puts "FAIL"; exit 1 }
    "foobar: \"43\""
}
